### ISSUE TITLE
letter J stays orange when your mod is enabled

### ISSUE THREAD

**Issue by jeffstokes72** [psychicEgg/EDHM#10]
Noticed it when I was looking at equipment, very consistently the J would remain orange the rest of the text was as expected.

**Comment by jeffstokes72** [comment]
It was in the area where you buy weapons, Ill get a couple screenshots.

**Comment by jeffstokes72** [comment]
![image](https://user-images.githubusercontent.com/9102841/102038480-60e56580-3d95-11eb-881d-dca0b98d63ef.png)
J in the word 'projectile'

**Comment by jeffstokes72** [comment]
![image](https://user-images.githubusercontent.com/9102841/102038537-81adbb00-3d95-11eb-9008-5362101d997c.png)
J in the livery box

**Comment by psychicEgg** [comment]
Hi Jeff, well spotted! Yeah that’s the ‘Orange J’ bug, though I hadn’t noticed it in the outfitting section before. Usually it’s found in the Info panel when it shows a notification you’re going to Jump to a new system.

I have no idea why Elite decides to swap the ‘j’ out of the main text shader, just to annoy me I think :) It only occurs at high resolutions and/or supersampling levels. 

There’s a fix for it in v1.32, but I made the fix optional as it reduced FPS for some people, although the impact on my FPS is very small. You can apply the fix (or remove the fix) by running the batch file in the elite-dangerous-64 directory (the EDHM batch, not the uninstall). However, I’m not sure if it fixes the orange j in Outfitting, I’ll have to check when I get home.

Thanks for letting me know

**Comment by jeffstokes72** [comment]
You bet, great tool you've made here, looking forward to trying the new update coming soon.

**Comment by psychicEgg** [comment]
Hi Jeff,

I've decided not to include the Orange J fix for v1.41 on Github for the reasons outlined here:
https://github.com/psychicEgg/EDHM/tree/main/Releases/v1.4/OrangeJ-Bug-Fix

But I'm happy to send it to you via Discord
psychicEgg#9971
