### ISSUE TITLE
With mod disabled, F6 still modifies the brightness of your own ship

### ISSUE THREAD

**Issue by jeffstokes72** [psychicEgg/EDHM#11]
title says it all. lmk if you need any info.

**Comment by alterNERDtive** [comment]
Define “mod disabled”. If you’re using the “kill switch” key bind it just disables messing with the shaders. Obviously all key binds still work.

**Comment by psychicEgg** [comment]
Hi Jeff, thanks for letting me know. I won't update the mod as it's not a game breaking bug, but I'll make sure it works correctly when I get around to modding the HUD in Odyssey.

Also, I still have to get the 'Orange J' fix compatible with the new version that you mentioned in another post .. just taking a few days break :) I hope you're enjoying the mod!

**Comment by jeffstokes72** [comment]
its a great mod!! I've shared with friends even. Have a good holiday
