### ISSUE TITLE
EDHM not working with Epic

### ISSUE THREAD

**Issue by stevan54** [psychicEgg/EDHM#12]
I run Frontier ED on my main account and EDHM works fine, but my alt account from Epic does not recognise EDHM. My other 3rd party apps work fine on both?

**Comment by alterNERDtive** [comment]
You installed ED twice in two different locations. Installing the mod to one cannot possibly affect the other.

**Comment by stevan54** [comment]
Then it is strange that my keybindings work for both installs and also EDProfiler affected both accounts, also Voiceattack works with both accounts.

**Comment by psychicEgg** [comment]
Hi Stevan, I installed my Epic version of Elite into a separate Windows account to prevent that overlap from occurring. Maybe try that and see if it fixes the issue?

Also, others are reporting some issues with ED Profiler making changes in a number of config files that affect the mod. If you install Elite into a separate windows account, maybe try running the mod before allowing ED Profiler to make changes

Please let me know if you get it working

**Comment by stevan54** [comment]
My apologies to all. I thought that the changes were made to files common to the two accounts (e.g. Voice attack, ED Profiler), but I reviewed my installs and there is a separate "elite-dangerous-64" folder for each install. So, I installed EDHM to the Epic folder "elite-dangerous-64" and copied over Profiles.ini and now both accounts are working with EDHM and have the same colour profiles.
psychicEgg - Great program, I am finding more and more as I use it. Thank you.

**Comment by alterNERDtive** [comment]
> Then it is strange that my keybindings work for both installs and also EDProfiler affected both accounts

Settings are saved in your `%appdata%`, not in the installation directory.

> also Voiceattack works with both accounts.

VoiceAttack doesn’t have anything to do with Elite. If you are talking about stuff like HCS or EDDI; those are accessing the journal files which are stored in your `Documents` folder, not in the installation directory.

In contrast injecting shaders requires you to mess with your game files in the installation directory. Entirely different thing.
