### ISSUE TITLE
Orange J Fix Missing?

### ISSUE THREAD

**Issue by bluedragon32** [psychicEgg/EDHM#13]
Just updated to 1.41, and I saw in the install instructions that the orange j fix had been removed from the main release but was still available on GitHub. Maybe I'm just blind, but I can't seem to find it.

**Comment by psychicEgg** [comment]
Hi, I've decided not to include the Orange J fix on Github for the reasons outlined here:
https://github.com/psychicEgg/EDHM/tree/main/Releases/v1.4/OrangeJ-Bug-Fix

But I'm happy to send it to you via Discord
psychicEgg#9971

**Comment by bluedragon32** [comment]
Ah, gotcha. Will do!
