### ISSUE TITLE
Hotas keybinding for profile selection

### ISSUE THREAD

**Issue by HammerPiano** [psychicEgg/EDHM#14]
Hi!

Is it possible to assign a hotas button to select a profile?

Currently, I see only way to select is modifier keys + regular keys

**Comment by psychicEgg** [comment]
Hi, sorry for the delay getting back to you. As far as I know there isn’t an in-built option in 3Dmigoto (the modding software) to bind a HOTAS button. Maybe there is, but it doesn’t come with a manual so I’m not sure of all the options.

Probably the best strategy would be to use macro software like Voice Attack or AutoHotKey, and set the HOTAS button to trigger a keyboard combo.
