### ISSUE TITLE
Mining Laser

### ISSUE THREAD

**Issue by M4DMAXX** [psychicEgg/EDHM#17]
Without the Mod you just see the Light of the Laser itself... and the Asteroid damage... now with Mod i see many green Lighting when i hit the Asteroid... its a bit bad for my eye :D 

Can i change it?

**Comment by psychicEgg** [comment]
Hi, EDHM doesn't modify the weapon visuals. Can you upload a screenshot as I'm not sure what you are referring to, thanks

**Comment by M4DMAXX** [comment]
Sure 

i send a Screenshot :)

**Comment by M4DMAXX** [comment]
actually my internet is broken... i message you with screenshot in discord when i got better connection
