### ISSUE TITLE
Station Services still in orange, no option to change that yet.

### ISSUE THREAD

**Issue by ThatMykl** [psychicEgg/EDHM#18]
Title says it all.. See the screenshots. Got the HUD set to my preferred colours but these panels don't change at all :( In DTEA's video for this, he could change at least some parts of it.. Am I missing something or has this been removed?

![image](https://user-images.githubusercontent.com/5021050/107755960-cd43fd00-6d23-11eb-8994-e5d0967d1d59.png)
![image](https://user-images.githubusercontent.com/5021050/107755985-d503a180-6d23-11eb-81d8-9ae94ada595a.png)

Cheers!

**Comment by psychicEgg** [comment]
Hi, I haven't started modding the panels yet. They'll take a long time due to all the little icons and sections, so will work on them if the mod survives the Odyssey update

**Comment by ThatMykl** [comment]
Ahh, I see, I'll be patient then :) thanks a lot for the quick reply ❤️ Keep up the great work 😘
