### ISSUE TITLE
Error when running EDHA

### ISSUE THREAD

**Issue by Brobi1Kenobi** [psychicEgg/EDHM#19]
I get a message when I try to run this. The message says "Unhandled Exception: Object reference not set to an instance of an object."

**Comment by alterNERDtive** [comment]
In the launcher? That is unrelated and a years old bug with Oculus. Have a copypasta.

If you are getting an “Object reference not set to an instance of an object” error when starting the Launcher with Oculus Home running (usually not on the first start, but subsequent ones), here’s the fix:

* Go to your Elite Installation folder. Default is IIRC `%programfiles%\EDLaunch`.
* Open `EDLaunch.exe.config`.
* You’ll see two lines reading `<supportedRuntime version="v4.0"/>` and `<supportedRuntime version="v2.0.50727"/>`. If you are getting the error, the 2.x one is on top.
* Swap the lines so the 4.0 one is on top.
* Save.
* ???
* Profit.

If you have copied your launcher for alt accounts (I have several `EDLaunch-<cmdr>.exe` files), do the same for the others. You might have to copy the file first (in my case, to `EDLaunch-<cmdr>.exe.config`).
