### ISSUE TITLE
hi excellent mod by the way just read the notes it said somthing about planet lines and unable to change due to another item that causes it to be included and mentioned if there was another way or idea to mention it i thought that perhaps space dust in normal flight might be an idea to differentiate between normal flight and supercriuse. im no modder and so my idea may be rubbish, but worth throwing it out there just incase brilliant mod again well done

### ISSUE THREAD

**Issue by xtcmrsly** [psychicEgg/EDHM#2]

**Comment by psychicEgg** [comment]
Hi, thanks very much for the suggestion! Space dust, that might actually work, I'll let you know

**Comment by psychicEgg** [comment]
You're a legend! The green lines are back
[https://i.imgur.com/SV3b7Bc.jpg](https://i.imgur.com/SV3b7Bc.jpg)

I'll have to update on the weekend as IRL is very busy atm.

What's your CMDR name so I can credit you on the update? (no worries if you prefer to be anonymous)

Thanks so much for the suggestion, I wouldn't have thought of it myself

**Comment by xtcmrsly** [comment]
Iam [XtC]MrSly of the Shadows of the Void

**Comment by xtcmrsly** [comment]
glad it worked

**Comment by xtcmrsly** [comment]
is it cheeky
![mr sly holo](https://user-images.githubusercontent.com/73955054/99110927-12e91080-25e3-11eb-9266-d2b3fbeb5e29.JPG)
 to ask if you can change the colour of the wobbly head txt icons

**Comment by xtcmrsly** [comment]
or after thinking about it, or as well can you colour the space dust, i don't know how you do this stuff, but if you could put a gradient filte,r over the dust so its rainbow coloured and changes as it passes centre screen that would be very cool,

**Comment by psychicEgg** [comment]
Hi CMDR, I don't mod any environmental elements, like space dust. Best to talk to the folks in the Immersion Mod thread on the Frontier forums .. they get into that sort of thing
https://forums.frontier.co.uk/threads/amazingly-realistic-immersion-mod.535240/

Also, FDev have said they are fine with the HUD Mod so long as we don't give an advantage to players or mod anything ARX related. The Bobbles are ARX items so we can't touch them, or modding will get banned. Sorry about that!

But thanks again for the suggestion about the normal flight mode detection .. still testing but I think it's working perfectly

o7

**Comment by xtcmrsly** [comment]
ah thats cool, im glad i could help and stoked about abouta mention in the update, its really great that dev allowed you to do your mod, its really taking o9ff you must be stoked too.

On 14 November 2020 at 0:44, psychicEgg <notifications@github.com> wrote:






Hi CMDR, I don't mod any environmental elements, like space dust. Best to talk to the folks in the Immersion Mod thread on the Frontier forums .. they get into that sort of thing
https://forums.frontier.co.uk/threads/amazingly-realistic-immersion-mod.535240/

Also, FDev have said they are fine with the HUD Mod so long as we don't give an advantage to players or mod anything ARX related. The Bobbles are ARX items so we can't touch them, or modding will get banned. Sorry about that!

But thanks again for the suggestion about the normal flight mode detection .. still testing but I think it's working perfectly

o7
