### ISSUE TITLE
Disable Keybinds after done configuring HUD colors

### ISSUE THREAD

**Issue by Merith-TK** [psychicEgg/EDHM#20]
Is there a way to disable all keybinds after i get HUD colors setup for myself?

**Comment by qzlearn** [comment]
yes,you can open KeyBinds.ini.And,you can add the ";" before the word.

**Comment by qzlearn** [comment]
like this image
![2021-03-06 172038](https://user-images.githubusercontent.com/47662497/110202053-4e189380-7ea1-11eb-82ae-bfc214191df1.png)
