### ISSUE TITLE
Feature Request - Red Emergency Mode (Toggle)

### ISSUE THREAD

**Issue by ITCMD** [psychicEgg/EDHM#21]
Having an option for an emergency mode where the lighting is red (or best case, flashing red and white) would be fantastic.

If at all possible to make a mode where you could set it to switch to emergency lighting, then go back to what you had set before, this could be really interesting to work with!

**Comment by psychicEgg** [comment]
Yeah I like that idea. Check out the start of the EDHM v1.5 video on YouTube .. that’s what I was thinking about for a stealth / silent running mode, which could also be an emergency mode. Currently I only have it working on the FDL but when I get some time I’ll see if I can get it working on the other ships

Unfortunately I can’t make any lights flash as that would be part of the game code. Would love to have that ability though

**Comment by ITCMD** [comment]
(Thanks for the response and thoughts, sorry I didnt reply until I saw it was closed!)
