### ISSUE TITLE
Having EDHM installed disables custom controls

### ISSUE THREAD

**Issue by thelinkr** [psychicEgg/EDHM#22]
i installed it on my copy of the game and found I couldn't use my customs bindings until uninstalling. my controls use my HOTAS, an XBox game pad, and the keyboard, I'm not sure if this is part of the issue or not, though I do need to turn the controller on in order for the game to recognize my custom control scheme at all.

**Comment by alterNERDtive** [comment]
That is unrelated _unless_ you used SteamInput to map stuff from controllers to something else. That might break when steam overlay isn’t running, and it conflicts with 3DMigoto.

> though I do need to turn the controller on in order for the game to recognize my custom control scheme at all.

If _any_ of the devices used in a control scheme are not present when you boot Elite, the control scheme will not be available.

**Comment by thelinkr** [comment]
My gamepad has a few buttons bound to keyboard keys through steam.

Ive tried booting Elite both with the gamepad off and on before hand, booting it then turning the controller on, and the same with the HOTAS. Before installing and after Uninstalling, all that i needed to do was turn the controller on and it will pop up in the preset drop down as custom as well as a few other unrelated options

**Comment by psychicEgg** [comment]
Hi, as alterNERDtive mentioned, Steam Overlay is incompatible with the modding software (3Dmigoto). As explained on page 2 of the EDHM Manual, the incompatibility will disable a controller mapped through Steam Overlay, and therefore Elite won't see it. If Elite doesn't see your controller then your Custom keybinds config won't load in-game.

I have a playstation controller running with Elite and EDHM, but Steam isn't active. 

There are various fixes others have used to solve this issue, please see this folder on the EDHM github
https://github.com/psychicEgg/EDHM/tree/main/PS-Xbox-Controller-fix

I hope that sorts it out

**Comment by rsobreviela** [comment]
Just an additional note.
I use Steam overlay to map my PS4 controller and I can confirm it works both on Horizons and Odyssey without the mod.
Once installed the mod, the controller **works** with Steam Overlay in Odyssey but **is not working** in Horizons using Steam Overlay as expected in the previous versions of the mod.
Uninstalling the mod enables the controller again.
