### ISSUE TITLE
Any plans to open source?

### ISSUE THREAD

**Issue by nick-strohm** [psychicEgg/EDHM#24]
Hey, do you have any plans to open source the project or at least having somebody working on it with you?

I'm experienced in reverse engineering from mostly analyzing and playing around with GTA 5 and I would like to help developing this mod.

Best regards

**Comment by psychicEgg** [comment]
Hi Nick, thanks for your message.

Unfortunately I can't make the mod open source .. if I did then I predict within a week someone would:

mod a paintjob + penis decal on their ship + post to reddit = banned mod and sad community

So for the sake of mod-preservation I have to keep it private, I hope that makes sense

However, you're welcome to join the EDHM community on discord
https://discord.gg/MtBszksjMr

**Comment by nick-strohm** [comment]
I already joined the discord and saw your progress on fixing the mod to work with odyssey. That's why I have been asking. But I do understand your point and how somebody could abuse it.

Have a good one o7
