### ISSUE TITLE
Odyssey

### ISSUE THREAD

**Issue by thenamesjay03** [psychicEgg/EDHM#25]
Hi I was just wondering if this is going to be updated to work in odyssey

**Comment by psychicEgg** [comment]
Hiya, yeah I'm updating the mod right now, it will take a while though. I estimate the front HUD and ship panels will take a few weeks, but the new station panels might take 1 to 2 months. 

I'll release the first version once the ship panels are done, but if you'd like to beta test the early versions you're welcome to join the discord
https://discord.gg/MtBszksjMr

**Comment by Merith-TK** [comment]
Why not leave the station panels as they are?

Considering this,
You, the player character, can customize your ships colorscheme to fit you, same with your Suit Hud, HOWEVER, you dont have control over station firmware, so things shown to you through the station panels, will use their colors

**Comment by alterNERDtive** [comment]
> You, the player character, can customize your ships colorscheme to fit you, same with your Suit Hud

Lore-wise, you can do neither.
