### ISSUE TITLE
Orbit lines are missing. They are enabled but just gone.

### ISSUE THREAD

**Issue by xX-Reef-Xx** [psychicEgg/EDHM#26]
I have the brightness set  as default in the  settings  but  they just aren't there.      i tweaked colours of a profile but     I did not touch orbit line settings   but they are just broken. no longer in game no matter what I do?    how do I fix this? please help  T.T

**Comment by psychicEgg** [comment]
Hi, this is for Horizons? I just updated my Horizons to FDev Patch 7, and reinstalled EDHM. The orbit lines and gravity lines appear to be ok, please see pic (orbit lines purple, gravity lines red)

https://i.imgur.com/1yhiDDB.png

I'm not sure why yours have disappeared. Did you reinstall EDHM after Patch 7? 

Open the file Startup-Profile.ini (in the EDHM-ini folder), and check the settings under this section

;------------------------------------------------------------------------------------------------------
; ** Orbit Lines (and Exclusion Zone Lines) & Gravity Well Lines ** (Supercruise only)
;------------------------------------------------------------------------------------------------------

Make sure these aren't 0 or missing:
; Orbit Lines Brightness. Try 0.05 or 0.1 for very dim lines. Turn off with 0.0
y117 = 0.3

; Gravity Well Lines Brightness (Normal range 0 to 1). Set to 0 to turn them off.
w117 = 0.1

**Comment by psychicEgg** [comment]
Update: I just checked Odyssey and they appear to be ok as well. I haven't touched the orbit lines shader in Odyssey so anything unusual there is all FDev.

A few things to keep in mind: to see orbit lines you must be in supercruise, and travelling faster than the minimum speed (> 30km/s)
