### ISSUE TITLE
Turn off lights around the commander's hands

### ISSUE THREAD

**Issue by sdfg2** [psychicEgg/EDHM#29]
I play in VR and EDHM is a godsend for making the HUD usable and turning off the obnoxious cabin lights for pretty VR exploring in the Asp and Krait.

One thing that causes a problem is the lights around the commander's throttle and joystick in game - the cyan and orange switches and stuff.  Could you add an option to turn them off?

**Comment by psychicEgg** [comment]
Yeah that's an option in the Horizons Explorer mode, but I haven't started it for Ody yet. Probably in a 2-3 weeks I'll do the Ody version as I have a long 'to do' list at the moment

**Comment by psychicEgg** [comment]
In the Cockpit Paint Mod you can set the colour and brightness of the HOTAS panel lights

The CPM is currently in development on the EDHM discord, and you're welcome to join the beta test
