### ISSUE TITLE
Allow hiding of on-foot centre dot

### ISSUE THREAD

**Issue by AMoonRabbit** [psychicEgg/EDHM#30]
I'd like to request this feature, if possible, for the removal/hiding of the centre dot which is present 100% of the time when on foot. I honestly don't know why Fdev have not given us the option in game, like they have with the mouse dot for ship HUD.

**Comment by psychicEgg** [comment]
Unfortunately it's not possible at this time. Please see this post on the Elite forums for more info

https://forums.frontier.co.uk/threads/elite-dangerous-hud-mod-edhm.557033/post-9920348
