### ISSUE TITLE
Auto-Update Breaks App

### ISSUE THREAD

**Issue by janagyjr** [psychicEgg/EDHM#31]
Windows 10 Pro 22H2
Auto-updating from one version to the next makes it un-launchable.
![image](https://user-images.githubusercontent.com/23646259/204894832-513c5eb0-dc35-4b02-974c-38a49f2f1ab8.png)

**Comment by psychicEgg** [comment]
Hi, the mod and the UI are two separate projects - I look after the modding component and Blue Mystic is the UI dev

I recommend leaving feedback for Blue Mystic on his [GitHub](https://github.com/BlueMystical/EDHM_UI), or you can chat with him directly on the [EDHM Discord](https://discord.gg/MtBszksjMr)

**Comment by janagyjr** [comment]
Honestly, it's not apparent which is problematic, so sorry to bother you.
