### ISSUE TITLE
Diamondback Scout missing from CPM plugin

### ISSUE THREAD

**Issue by AMoonRabbit** [psychicEgg/EDHM#32]
Diamondback Scout appears to be missing from the CPM ship list from the CPM menu, but is present in the "Cockpit Mod For" field selection. 

I have tested with DBE mods on the DBS but nothing changes. 
![image](https://user-images.githubusercontent.com/3766988/232051789-cf3f6b84-1782-4683-a163-09e2fd8cf14a.png)
![image](https://user-images.githubusercontent.com/3766988/232052254-5adfa19b-d296-4ebe-89ce-a60c2b55786b.png)

**Comment by psychicEgg** [comment]
Hi, the ini file for the Cockpit Paint Mod is difficult to update (it doesn't automatically update like the main mod). So I included every ship in the list so the file doesn't need to be updated at a later date. 

You can view which ships have been modded here:
https://github.com/psychicEgg/EDHM/blob/main/Odyssey/3rdPartyMods/CockpitPaintMod/ShipList.md

Only the DBE has been modded at this time.

**Comment by AMoonRabbit** [comment]
Okay, thank you for the response. Seeing as it's not a bug, I will go ahead and mark this issue as closed.
