### ISSUE TITLE
Color Format Definition for Each Element

### ISSUE THREAD

**Issue by BlueMystical** [psychicEgg/EDHM#4]
Hi there,

It is necessary that you define in each Color Table, the Color Format to be used, either **ARGB** or **RGBA**, i found that ShipHolo uses **ARGB** but then you told this guy [at the forums](https://forums.frontier.co.uk/threads/elite-dangerous-hud-mod-edhm.557033/page-4) to use RGBA, so... having Different Formats will be a problem when translating Colors, unless the format to be used is specified, because a color will become another very different:

RGBA (**255,255,0**,0) <- Yellow
ARGB (**0,255,255**,0)  <- Cyan

Also, need to confirm if the Alpha part of such Colors will be considered or replaced with Zeros IN ALL CASES.

Regards.

**Comment by psychicEgg** [comment]
Unfortunately I don't have any control over the output, it's done within 3dmigoto. Sometimes I find values in strange positions.

I can only describe the output, I can't change the order of things.

Sometimes the 0 or 1 at the end (or the beginning) of a colour string is a dummy variable. If there's a real alpha channel (some elements don't have an independent alpha channel) then I'll specify it in the template

Sorry about that, but it's not something I can control

**Comment by BlueMystical** [comment]
Seems you misread my request,
Not asking to change anything, just to specify which Color Format must be used when translating colors with each of the color calibration tables, that's all.

**Comment by psychicEgg** [comment]
This is an example from the combat HUD .. isn't that what's already there?

--------------------------------------------
Red: First value in example below
Green: Second value in example below 
Blue: Third value in example below
Alpha/transparency: Fourth value in example below (default = 1.000000; EDHM pre-configured mod default = 0.800000)

Line 77
  mul r1.xyzw, r0.xxxw, l(0.260000, 0.270000, 0.400000, 1.000000)

**Comment by BlueMystical** [comment]
So, combat HUD uses RGBA and has the Alpha channel at 1 but Ship Holo uses ARGB and u told me to set its alpha to Zero, what about the other elements?...
Ya know what? forget about it, i'll figure it out by the old trial and error method.
Regards.
