### ISSUE TITLE
Steam Remote play incompatability

### ISSUE THREAD

**Issue by Tebryn** [psychicEgg/EDHM#5]
Unable to use Steam Remote Play (Also referred to as 'In-Home Streaming') 

I've been playing Elite on an older laptop while my main PC was running the game through Steam's Remote Play feature. but after resetting my XML and installing this mod all I get is a black screen when connecting. (game and mod function normally on Main PC)

I first launch ED launcher through steam, then launch ED as normal on the Main PC. I then go to my laptop pc and connect (logged into my Steam account on both, I see that ED is running on the Main PC from the laptop) after connecting for the first time, it rebroadcasts the ED Launcher. Closing that out will transfer the broadcast to the ED executable. where i can then take control of the game and play normally. But instead of seeing the game after closing out the ED Launcher, I just get a black screen. 

Re-Connecting doesn't resolve the problem (usually if there are connection issues, I can tab out of the connection on the laptop, stop and re-connect straight back into the ED executable)

After Uninstalling the mod with the .bat I was able to connect and play via Remote Play normally again. 

I understand that this might be a fairly edge case as far as the normal user, but I figured it would be worth mentioning. 
I am also one of the users that doesn't have a functioning Steam Overlay while playing with the mod enabled. Although Radeon overlay seemed to work fine. 

I also don't have a Steam Link to test and see if the issue is duplicated there. 

All settings set to recommended levels per Installation instructions
Game Set to Borderless 
OS: Windows 10 x64
Game and screen resolution: 2560x1440 @90hz
GPU: AMD Radeon RX 5700
GPU Driver Version: 20.45.01.18-201113a-361134C-RadeonSoftwareAdrenalin2020
Game Running on Secondary monitor (both monitors run same resolution and refresh rate)
The resolution of the connected stream is at 1440x810 @60fps after capture and rebroadcast to the laptop.

**Comment by psychicEgg** [comment]
Thanks very much for reporting the issue. I'll refer back to your post if someone experiences the same black screen when using Steam Remote Play.

But it will have something to do with the modding software 3Dmigoto rather than ED HUD Mod specifically. Unfortunately the developer of 3Dmigoto is no longer updating the software so I don't think there will be a fix incoming. But if you manage to find a workaround I'd be grateful if you could please let me know.

o7
