### ISSUE TITLE
How do I change the planets from GREEN to something that matches my color scheme?

### ISSUE THREAD

**Issue by eyeonus** [psychicEgg/EDHM#6]
It says there's instructions on here, but I cannot find them for the life of me.

**Comment by psychicEgg** [comment]
Hiya, the instructions already on the github refer to the radar proper (the base grid and pulse lines), not the radar bodies. In the next update I'll specify the locations where you can make changes to the bodies, as I've divided them into suns/stars (yellow), planets (green) and moons (blue), but that demarcation wasn't available in v1.32

They can be a bit tricky to balance correctly as the components are split across four separate shaders - the planetary bodies, the ships, elevation lines and coasters (solid circles). But you'll be able to play around with them to match your colour scheme

**Comment by eyeonus** [comment]
AWESOME! Keep up the good work, much appreciated!

**Comment by fido1990** [comment]
Hello Egg, thanks for the great mod... Was there any update on this issue? I'd like to change the planet colors, but had no luck finding it in documentation you attached to the mod... Thank you!

**Comment by psychicEgg** [comment]
> Hello Egg, thanks for the great mod... Was there any update on this issue? I'd like to change the planet colors, but had no luck finding it in documentation you attached to the mod... Thank you!

Hiya, the general feedback was the mod was becoming too complex with too many options, so I didn’t include options to change various smaller elements, such as the bodies on the supercruise radar. However, when I adapt the mod to Odyssey (every shader has changed) I’ll be making a ‘tweaker’s paradise’ version for enthusiasts who would like to choose the colour of every little element, including the radar body colours. It should be available around the launch of Odyssey, but if it’s any earlier I’ll announce it on the Elite forums

**Comment by fido1990** [comment]
oh man, that is to great! thank you so much for your work... looking forward for that...!

I know this is really off topic, but I don't want to create another thread / bug, but is there any way to do something about some of the lights being completely blacked out, even when lights are "on" in the mod? It can be seen very well in for example Krait mk.2 cockpit, both in front of the pilot, and over the shoulder on the ceiling... Thank you again!
