### ISSUE TITLE
Steam, some problems.

### ISSUE THREAD

**Issue by alxxxx** [psychicEgg/EDHM#7]
After installing the mod, the F12 button stopped working (it is used by Steam to create screenshots). 
The Steam FPS counter also stopped working.

**Comment by psychicEgg** [comment]
Hi, yes the modding software (3Dmigoto) isn’t compatible with Steam overlay. I use either the in-game screenshots or the PrtScrn key

Elite also has an in-built FPS counter, activate/deactivate with CTRL F
