### ISSUE TITLE
Steam Screenshot F12 broken when installed

### ISSUE THREAD

**Issue by revalundale** [psychicEgg/EDHM#9]
After testing from multiple users, the Steam screenshot F12 has been reported as not working with the HUD Mod installed.

**Comment by psychicEgg** [comment]
Hi, yes the modding software (3Dmigoto) isn’t compatible with Steam overlay. I use either the in-game screenshots or the PrtScrn key

**Comment by rsowles** [comment]
is there any plans to get this to work with steam? The screen shots are a ton better with steam..

**Comment by psychicEgg** [comment]
I didn’t create 3Dmigoto, I just use it to mod Elite. You’d have to ask the developer who created 3dmigoto, but I have a feeling he’s not updating it anymore

**Comment by TIMON72** [comment]
@psychicEgg maybe directly create an issue to the developer (https://github.com/bo3b/3Dmigoto/issues)? At least with the problems of launching some games, he answers today. I just sometimes want to publish screenshots in Steam.
